# AlpsPS/2 protocol packet size in bytes
# Set accordingly to your ALPS device HW protocol
# Typically, the size is 6 bytes, but for your device,
# it may very well be different (e.g. AlpsPS/2 v4 uses
# packets of 8 bytes)
ALPS_PACKET_SIZE = 6

# Dump AlpsPS/2 packets
# Each packet is dumped to the kernel ring buffer.
# Use show_pkt.pl script to extract them and analyse further.
# Note that if the device produces raw 3 byte PS/2 packets,
# nothing shall be dumped.
# In that case, you need to experiment with your device HW initialisation
# (see the driver documentation for more info).
ALPS_PACKET_DUMP = yes

# Don't process AlpsPS/2 packets
# Setting this to "yes" is only meaningful if ALPS_PACKET_DUMP is set to "yes".
# Otherwise, the driver will just silently discard the packets...
# Note that again, that's not the case of raw PS/2 packets
ALPS_PACKET_NO_PROCESS = yes
